replicaCount: 1
fullNameOverride: "rabbitmq"
image:
  registry: uhub.service.ucloud.cn
  repository: entropypool/rabbitmq
  tag: 3.9.7
  pullPolicy: IfNotPresent
auth:
  username: user
  existingPasswordSecret: rabbitmq
